config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'splash_screen#index'
   
   resources :splash_screen, only: %i[index]
   resources :users, only: %i[index show] do 
    resources :groups do
       resources :entities
    end   
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Group, user_id: user.id
      can :manage, Entity, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities

  validates :name, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: true }
  validates :password, length: { in: 6..20 }
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @entity = Entity.new
    @user = current_user
    @groups = Group.where(user: @user)
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.author = current_user

    if @entity.save
      redirect_to user_group_path(current_user, params[:group_id]), notice: 'Transaction added succesfully'
    else
      render :new, notice: 'Ooops, something went wrong'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_ids)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = current_user
    @groups = Group.order(:created_at).where(user: @user)
    @total = 0
    @groups.each do |group|
      @total += group.entities.sum(:amount)
    end
  end

  def show
    @user = current_user
    @group = Group.find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
    @total = @group.entities.sum(:amount)
  end

  def new
    @user = current_user
    @group = Group.new
  end

  def create
    @group = Group.new group_params
    @group.user = current_user

    if @group.save
      redirect_to user_groups_path(current_user), notice: 'Category added successfully'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index
    redirect_to user_groups_path(current_user) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/new.html.erb
<div class='container'>
  <%= form_with model: @entity,  url: user_group_entities_path(params[:user_id], params[:group_id]), method: 'post', class: "flex-column form", id:'transaction_form' do |form| %>
    <header class="header flex-row">
      <div>
        <%= link_to user_group_path(params[:user_id],  params[:group_id]) do %>
            <%= image_tag('left-arrow.png', size: "20x20") %>
          <% end %>
      
      </div>
      <div class="title">
        NEW TRANSACTION
      </div>
      <div>
        <button id="submit_button" class='submit' >Save</button>
      </div>

    </header>
    <%= render partial: 'shared/messages' %>
    <%= form.text_field :name, id:'name', autofocus: true, placeholder:'Transaction name', required: true %>
    <%= form.number_field :amount, id:'amount', step: 0.01, min:0.01, placeholder:'Amount', required: true %>
    <%= form.select :group_ids, @groups.map { |t| [t.name, t.id]}, { :prompt =>'Select category'}, required: true %>
    <% end %>
</div>

app/views/groups/index.html.erb
<div class="container flex-column">
   <%= render partial: 'shared/header', locals: {:title=> 'CATEGORIES', :back_button => false, :form_id=> '' } %>
  <div class="total-amount flex-row justify-space-between">
    <span class='bold'>Total amount:</span>
    <span class='bold'>$<%= '%.2f' % @total %></span>
  </div>
  <%= render partial:'shared/messages'%>
 
<ul class='list flex-column'>
  <% @groups.each do |group|%>
    <li class='card flex-row'>
      <%= image_tag(group.icon, class: 'icon') %>
      <div class='group-info flex-row'>
        <div class='flex-column justify-space-between'>
          <%= link_to user_group_path(params[:user_id], group) do %>
            <h3><%= group.name %></h3>
          <% end %>
          <span>
            <%= group.created_at.strftime("%d") %>
            <%= I18n.t("date.abbr_month_names")[group.created_at.strftime("%m").to_i]%>
            <%= group.created_at.strftime("%Y")%>
          <span>
          
        </div>
        <div>
          <span class='bold'>$<%= '%.2f' % group.entities.sum(:amount) %></span>
        </div>
      </div>
      
    </li>
  <% end %>
</ul>

<%= link_to  'ADD CATEGORY', new_user_group_path(@user), class:'add-button' %>

</div>

app/views/groups/new.html.erb
<div class='container'>
  <%= form_with model: @group,  url: user_groups_path(params[:user_id]), method: 'post', class: "flex-column form", id:'category_form' do |form| %>
    <%= render partial: 'shared/header', :locals => { :title => "NEW CATEGORY", :back_url => user_groups_path, :back_button => true,  :form_id => 'category_form', :action_button =>'Save'  } %>
    <%= render partial:'shared/messages'%>
    <%= form.text_field :name, autofocus: true, placeholder:'Category name' %>
    <%= form.hidden_field :icon %>
     <% icons = ['food', 'sport', 'transportation', 'book', 'bank', 'entertainment', 'invoice', 'computer', 'education'] %>
    <%= field_set_tag 'Select category icon', class:'icons' do %>
        <% icons.each do |icon|%>
        <%= image_tag(icon, class:'category-icon selected', id:icon) %>
      <% end %>
    <% end %>
    
  <% end %>
</div>
<script>
  let icons = document.querySelectorAll('.category-icon')
  let icon_id = document.querySelector('#group_icon')
  icons.forEach(icon => {
    icon.className='category-icon'
    icon.addEventListener('click', (event)=>{
      icons.forEach(i=>i.classList.remove('selected'))
      icon.classList.add('selected')
      icon_id.value = event.target.id
    })
  });
</script>

app/views/groups/show.html.erb
<div class="container flex-column">
 <%= render partial: 'shared/header', :locals => { :title => "TRANSACTIONS", :back_url => user_groups_path, :back_button => true, :form_id=> ''  } %>
 <div class="total-amount flex-row justify-space-between">
    <span class='bold'><%= @group.name %> (total amount):</span>
    <span class='bold'>$<%= '%.2f' % @total %></span>
  </div>
  <%= render partial:'shared/messages'%>

<ul class='list flex-column'>
  <% @entities.each do |entity|%>
    <li class='card flex-row'> 
      <div class='group-info flex-row'>
        <div class='flex-column '>
          <h3><%= entity.name %></h3>
          <span class='date'>
              <%= entity.created_at.strftime("%d") %>
              <%= I18n.t("date.abbr_month_names")[entity.created_at.strftime("%m").to_i]%>
              <%= entity.created_at.strftime("%Y")%>
          <span>
        </div>
      <span class='bold'>$<%= '%.2f' % entity.amount %></span>
      </div>

    </li>
  <% end %>
</ul>

<%= link_to  'ADD TRANSACTION', new_user_group_entity_path(@group.user, @group), class:'add-button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <%= yield %>

  </body>
</html>

app/views/shared/_header.html.erb
<header class="header flex-row">
  <div>
    <%  if back_button  %>
      <%= link_to back_url do %>
      <%= image_tag('left-arrow.png', size: "20x20") %>
      <% end %>
    <% end %>
  </div>
  <div class="title">
    <%= title %>
  </div>
  <div>
  
    <% if form_id !='' %>
        <button id="submit_button"onClick="document.getElementById('checked_items').value > 0 ? document.getElementById('<%= form_id %>').submit: false" class='submit' ><%= action_button %></button>
      <% else %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <%= image_tag('log-out.png', size: "20x20") %>
        <% end %>
    <% end %>
  </div>

</header>

app/views/shared/_messages.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/splash_screen/index.html.erb
<div class='container flex-column'>
  <div class="logo">
    <h1>Expense<span>Tracker<span></h1>
  </div>
  
  <div class='buttons flex-column'>
    <%= link_to 'LOG IN', new_user_session_path, class:"login" %>
    <%= link_to 'SIGN UP', new_user_registration_path, class:"link" %>
  </div>
</div>